// Generates PostgreSQL seed scripts (db/seed/*.sql) from the curated Excel datasets.
//
//   cd db && npm install && npm run gen
//
// Output is mounted into the Postgres container's /docker-entrypoint-initdb.d, so the
// database seeds itself on first `docker compose up`. Re-run this whenever the source
// Excel files change, then `docker compose down -v && docker compose up -d` to reseed.

import XLSX from 'xlsx';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, 'source');
const OUT = join(__dirname, 'seed');
mkdirSync(OUT, { recursive: true });

// Curated single-sheet source (from extract-source.mjs) -> Postgres table.
const TABLES = [
  { file: 'automotive.xlsx',    table: 'automotive' },
  { file: 'retail.xlsx',        table: 'retail' },
  { file: 'manufacturing.xlsx', table: 'manufacturing' },
  { file: 'healthcare.xlsx',    table: 'healthcare' },
  { file: 'energy.xlsx',        table: 'energy' },
];

// "VEHICLE CLASS" -> vehicle_class, "Order ID" -> order_id, "Production_Line_ID" -> production_line_id
const snake = (h) =>
  String(h).trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .split(/[^A-Za-z0-9]+/).filter(Boolean)
    .join('_').toLowerCase() || 'col';

function inferType(values) {
  let allInt = true, allNum = true, allDate = true, any = false, maxAbs = 0;
  for (const v of values) {
    if (v === null || v === undefined || v === '') continue;
    any = true;
    if (v instanceof Date) { allNum = false; allInt = false; }
    else if (typeof v === 'number') {
      allDate = false;
      if (!Number.isInteger(v)) allInt = false;
      maxAbs = Math.max(maxAbs, Math.abs(v));
    } else {
      allNum = false; allInt = false;
      if (!/^\d{4}-\d{2}-\d{2}/.test(String(v))) allDate = false;
    }
  }
  if (!any) return 'TEXT';
  if (allInt) return maxAbs > 2147483647 ? 'BIGINT' : 'INTEGER';
  if (allNum) return 'DOUBLE PRECISION';
  if (allDate) return 'DATE';
  return 'TEXT';
}

function sqlVal(v, type) {
  if (v === null || v === undefined || v === '') return 'NULL';
  if (type === 'DATE') {
    const d = (v instanceof Date) ? v : new Date(v);
    return isNaN(d) ? 'NULL' : `'${d.toISOString().slice(0, 10)}'`;
  }
  if (type === 'INTEGER' || type === 'BIGINT' || type === 'DOUBLE PRECISION') {
    const n = (typeof v === 'number') ? v : Number(v);
    return isNaN(n) ? 'NULL' : String(n);
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

let idx = 10;
for (const t of TABLES) {
  const wb = XLSX.readFile(join(SRC, t.file), { cellDates: true });
  const ws = wb.Sheets[wb.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json(ws, { defval: null, raw: true });
  if (!rows.length) { console.warn('  no rows in', t.file); continue; }

  const cols = Object.keys(rows[0]).map((h) => ({ src: h, name: snake(h) }));
  const seen = {};
  for (const c of cols) { let n = c.name, i = 2; while (seen[n]) n = `${c.name}_${i++}`; seen[n] = 1; c.name = n; }
  for (const c of cols) c.type = inferType(rows.map((r) => r[c.src]));

  let sql = `-- ${t.table}: ${rows.length} rows (auto-generated by gen-seed.mjs)\n`;
  sql += `DROP TABLE IF EXISTS ${t.table};\n`;
  sql += `CREATE TABLE ${t.table} (\n`;
  sql += cols.map((c) => `    ${c.name} ${c.type}`).join(',\n') + '\n);\n\n';

  const CHUNK = 1000;
  const colList = cols.map((c) => c.name).join(', ');
  for (let i = 0; i < rows.length; i += CHUNK) {
    const chunk = rows.slice(i, i + CHUNK);
    sql += `INSERT INTO ${t.table} (${colList}) VALUES\n`;
    sql += chunk.map((r) => '(' + cols.map((c) => sqlVal(r[c.src], c.type)).join(', ') + ')').join(',\n') + ';\n\n';
  }

  const fname = `${idx}_${t.table}.sql`;
  writeFileSync(join(OUT, fname), sql);
  console.log(`${t.table.padEnd(14)} ${String(rows.length).padStart(6)} rows  ${cols.length} cols  -> seed/${fname}`);
  console.log('   ' + cols.map((c) => `${c.name}:${c.type}`).join(', '));
  idx += 10;
}
console.log('\nDone. Seed scripts written to db/seed/.');
